### ISSUE TITLE
Fix attendeesInfo null in EventDetails

### ISSUE THREAD

**Issue by zzfz1** [murwaneisa/HKIF-APP#106]
I encountered this issue when clicking on the event details from the home page.

Weirdly if the event has an empty attendeesIds array, then the bug won't occur.

![Image](https://github.com/murwaneisa/HKIF-APP/assets/86393880/c43af036-a738-4bac-b2d0-4147dd407eb7)

![Image](https://github.com/murwaneisa/HKIF-APP/assets/86393880/70c2019b-78ea-4b2d-acdf-9e3e27b87b4f)

**Comment by ahmedmohd957** [comment]
![Screenshot from 2024-03-15 23-35-54](https://github.com/murwaneisa/HKIF-APP/assets/57142824/cba063b0-09d0-4426-91d8-112999f7afd3)

It was causing issue because "uid" was undeclared but i think the issue can be fixed by adding "let" before "uid" in the for loop.

**Comment by zzfz1** [comment]
@ahmedmohd957 Yeah it works! Thanks a lot!

I'll include this fix in my commit to event-management/authentication branch.
