### ISSUE TITLE
Setting up Axios

### ISSUE THREAD

**Issue by murwaneisa** [murwaneisa/HKIF-APP#30]
**Dependent Branch(es)**
main/setup-axios

**Functionality**
setup Axios for HTTP request 

**Additional Notes**

**Comment by zzfz1** [comment]
## Can not Use main/setup-axios
fatal: cannot lock ref 'refs/heads/main/setup-axios': 'refs/heads/main' exists; cannot create 'refs/heads/main/setup-axios'

## Changed Dependent Branch to feature/axios-setup

**Comment by zzfz1** [comment]
@murwaneisa 
## Unsolved problem
Now with localhost server, axios can make requests from web but not android or iOS.
### Solution
1. Use emulators for testing, BaseURL for Android should be replaced with http://10.0.2.2/ and configure adb port mapping.
2. Use actual LAN address of the localhost server (laptop)
