### ISSUE TITLE
Authentication for event management

### ISSUE THREAD

**Issue by murwaneisa** [murwaneisa/HKIF-APP#97]
Dependent Branch(es)
event-management/authentication

Functionality
If the admin isn't an event manager, he/she can't edit/add events,

* If he/she clicks add an event, pop up an alert.

* If he/she clicks view event, navigate them to the normal user eventDetails page.

Additional Notes

**Comment by zzfz1** [comment]
* Add EventDetails in the Admin stack
* Rename the Event Managment entry

**Comment by zzfz1** [comment]
Waiting for #106 to fix
